export type MenuItemTypes = {
    key: string;
    label: string;
    isTitle?: boolean;
    icon?: string;
    url?: string;
    badge?: {
        variant: string;
        text: string;
    };
    parentKey?: string;
    target?: string;
    children?: MenuItemTypes[];
};

const MENU_ITEMS: MenuItemTypes[] = [
    { key: 'navigation', label: 'NAVIGATION', isTitle: true },
    {
        key: 'dashboard',
        label: 'Dashboard',
        isTitle: false,
        icon: 'mdi mdi-view-dashboard-outline',
        badge: { variant: 'success', text: '9+' },
        url: '/dashboard',
    },
    { key: 'apps', label: 'APPS', isTitle: true },
    {
        key: 'tasks',
        label: 'Tasks',
        isTitle: false,
        icon: 'mdi mdi-clipboard-outline',
        url: '/tasks',
        children: [
            {
                key: 'tasks-kanban-board',
                label: 'Kanban Board',
                isTitle: false,
                url: '/tasks/kanban-board',
                parentKey: 'tasks',
            },
            {
                key: 'tasks-details',
                label: 'Details',
                isTitle: false,
                url: '/tasks/details',
                parentKey: 'tasks',
            },
        ],
    },
    { key: 'custom', label: 'CUSTOM', isTitle: true },
    {
        key: 'auth',
        label: 'Auth Pages',
        isTitle: false,
        icon: 'mdi mdi-account-multiple-plus-outline',
        children: [
            {
                key: 'auth-login',
                label: 'Log In',
                isTitle: false,
                url: '/auth/login',
                parentKey: 'auth',
            },
            {
                key: 'auth-register',
                label: 'Register',
                isTitle: false,
                url: '/auth/register',
                parentKey: 'auth',
            },
            {
                key: 'auth-forget-password',
                label: 'Recover Password',
                isTitle: false,
                url: '/auth/forget-password',
                parentKey: 'auth',
            },
            {
                key: 'auth-lock-screen',
                label: 'Lock Screen',
                isTitle: false,
                url: '/auth/lock-screen',
                parentKey: 'auth',
            },
        ],
    },
    {
        key: 'pages',
        label: 'Extra Pages',
        isTitle: false,
        icon: 'mdi mdi-file-multiple-outline',
        children: [
            {
                key: 'starter',
                label: 'Starter',
                isTitle: false,
                url: '/pages/starter',
                parentKey: 'pages',
            },
            {
                key: 'pricing',
                label: 'Pricing',
                isTitle: false,
                url: '/pages/pricing',
                parentKey: 'pages',
            },
            {
                key: 'timeline',
                label: 'Timeline',
                isTitle: false,
                url: '/pages/timeline',
                parentKey: 'pages',
            },
            {
                key: 'invoice',
                label: 'Invoice',
                isTitle: false,
                url: '/pages/invoice',
                parentKey: 'pages',
            },
            {
                key: 'faq',
                label: 'FAQs',
                isTitle: false,
                url: '/pages/faq',
                parentKey: 'pages',
            },
            {
                key: 'gallery',
                label: 'Gallery',
                isTitle: false,
                url: '/pages/gallery',
                parentKey: 'pages',
            },
            {
                key: 'error-404',
                label: 'Error 404',
                isTitle: false,
                url: '/error-404',
                parentKey: 'pages',
            },
            {
                key: 'error-500',
                label: 'Error 500',
                isTitle: false,
                url: '/error-500',
                parentKey: 'pages',
            },
            {
                key: 'maintenance',
                label: 'Maintenance',
                isTitle: false,
                url: '/maintenance',
                parentKey: 'pages',
            },
            {
                key: 'coming-soon',
                label: 'Coming Soon',
                isTitle: false,
                url: '/coming-soon',
                parentKey: 'pages',
            },
            {
                key: 'landing',
                label: 'Landing',
                isTitle: false,
                url: '/landing',
                parentKey: 'pages',
            },
        ],
    },
    {
        key: 'projects',
        label: 'Projects',
        isTitle: false,
        icon: 'mdi mdi-briefcase-variant-outline',
        url: '/projects',
    },
    { key: 'components', label: 'COMPONENTS', isTitle: true },
    {
        key: 'base-ui',
        label: 'Base UI',
        isTitle: false,
        icon: 'mdi mdi-briefcase-outline',
        children: [
            {
                key: 'buttons',
                label: 'Buttons',
                isTitle: false,
                url: '/base-ui/buttons',
                parentKey: 'base-ui',
            },
            {
                key: 'cards',
                label: 'Cards',
                isTitle: false,
                url: '/base-ui/cards',
                parentKey: 'base-ui',
            },
            {
                key: 'avatars',
                label: 'Avatars',
                isTitle: false,
                url: '/base-ui/avatars',
                parentKey: 'base-ui',
            },
            {
                key: 'tabs-accordions',
                label: 'Tabs & Accordions',
                isTitle: false,
                url: '/base-ui/tabs-accordions',
                parentKey: 'base-ui',
            },
            {
                key: 'modals',
                label: 'Modals',
                isTitle: false,
                url: '/base-ui/modals',
                parentKey: 'base-ui',
            },
            {
                key: 'progress',
                label: 'Progress',
                isTitle: false,
                url: '/base-ui/progress',
                parentKey: 'base-ui',
            },
            {
                key: 'notifications',
                label: 'Notifications',
                isTitle: false,
                url: '/base-ui/notifications',
                parentKey: 'base-ui',
            },
            {
                key: 'offcanvas',
                label: 'Offcanvas',
                isTitle: false,
                url: '/base-ui/offcanvas',
                parentKey: 'base-ui',
            },
            {
                key: 'placeholders',
                label: 'Placeholders',
                isTitle: false,
                url: '/base-ui/placeholders',
                parentKey: 'base-ui',
            },
            {
                key: 'spinners',
                label: 'Spinners',
                isTitle: false,
                url: '/base-ui/spinners',
                parentKey: 'base-ui',
            },
            {
                key: 'images',
                label: 'Images',
                isTitle: false,
                url: '/base-ui/images',
                parentKey: 'base-ui',
            },
            {
                key: 'carousel',
                label: 'Carousel',
                isTitle: false,
                url: '/base-ui/carousel',
                parentKey: 'base-ui',
            },
            {
                key: 'embedvideo',
                label: 'Embed Video',
                isTitle: false,
                url: '/base-ui/embedvideo',
                parentKey: 'base-ui',
            },
            {
                key: 'dropdowns',
                label: 'Dropdowns',
                isTitle: false,
                url: '/base-ui/dropdowns',
                parentKey: 'base-ui',
            },
            {
                key: 'popovers-tooltips',
                label: 'Tooltips & Popovers',
                isTitle: false,
                url: '/base-ui/popovers-tooltips',
                parentKey: 'base-ui',
            },
            {
                key: 'general',
                label: 'General UI',
                isTitle: false,
                url: '/base-ui/general',
                parentKey: 'base-ui',
            },
            {
                key: 'typography',
                label: 'Typography',
                isTitle: false,
                url: '/base-ui/typography',
                parentKey: 'base-ui',
            },
            {
                key: 'grid',
                label: 'Grid',
                isTitle: false,
                url: '/base-ui/grid',
                parentKey: 'base-ui',
            },
        ],
    },
    {
        key: 'widgets',
        label: 'Widgets',
        isTitle: false,
        icon: 'mdi mdi-gift-outline',
        url: '/widgets',
    },
    {
        key: 'extended-ui',
        label: 'Extended UI',
        isTitle: false,
        icon: 'mdi mdi-layers-outline',
        badge: { variant: 'info', text: 'Hot' },
        children: [
            {
                key: 'nestable',
                label: 'Nestable',
                isTitle: false,
                url: '/extended-ui/nestable',
                parentKey: 'extended-ui',
            },
            {
                key: 'rangesliders',
                label: 'Range Sliders',
                isTitle: false,
                url: '/extended-ui/rangesliders',
                parentKey: 'extended-ui',
            },
            {
                key: 'sweet-alert',
                label: 'Sweet Alert',
                isTitle: false,
                url: '/extended-ui/sweet-alert',
                parentKey: 'extended-ui',
            },
            {
                key: 'tour',
                label: 'Tour',
                isTitle: false,
                url: '/extended-ui/tour',
                parentKey: 'extended-ui',
            },
            {
                key: 'treeview',
                label: 'Tree View',
                isTitle: false,
                url: '/extended-ui/treeview',
                parentKey: 'extended-ui',
            },
        ],
    },
    {
        key: 'icons',
        label: 'Icons',
        isTitle: false,
        icon: 'mdi mdi-shield-outline',
        children: [
            {
                key: 'feather',
                label: 'Feather Icons',
                isTitle: false,
                url: '/icons/feather',
                parentKey: 'icons',
            },
            {
                key: 'mdi',
                label: 'Material Design IIcons',
                isTitle: false,
                url: '/icons/mdi',
                parentKey: 'icons',
            },
            {
                key: 'dripicons',
                label: 'Dripicons',
                isTitle: false,
                url: '/icons/dripicons',
                parentKey: 'icons',
            },
            {
                key: 'font-awesome',
                label: 'Font Awesome 5',
                isTitle: false,
                url: '/icons/font-awesome',
                parentKey: 'icons',
            },
            {
                key: 'themify',
                label: 'Themify',
                isTitle: false,
                url: '/icons/themify',
                parentKey: 'icons',
            },
        ],
    },
    {
        key: 'forms',
        label: 'Forms',
        isTitle: false,
        icon: 'mdi mdi-texture',
        children: [
            {
                key: 'basic',
                label: 'General Elements',
                isTitle: false,
                url: '/forms/basic',
                parentKey: 'forms',
            },
            {
                key: 'advanced',
                label: 'Advanced',
                isTitle: false,
                url: '/forms/advanced',
                parentKey: 'forms',
            },
            {
                key: 'validation',
                label: 'Validation',
                isTitle: false,
                url: '/forms/validation',
                parentKey: 'forms',
            },
            {
                key: 'wizard',
                label: 'Wizard',
                isTitle: false,
                url: '/forms/wizard',
                parentKey: 'forms',
            },
            {
                key: 'upload',
                label: 'File Upload',
                isTitle: false,
                url: '/forms/upload',
                parentKey: 'forms',
            },
            {
                key: 'editors',
                label: 'Editors',
                isTitle: false,
                url: '/forms/editors',
                parentKey: 'forms',
            },
        ],
    },
    {
        key: 'tables',
        label: 'Tables',
        isTitle: false,
        icon: 'mdi mdi-table',
        children: [
            {
                key: 'basic',
                label: 'Basic Table',
                isTitle: false,
                url: '/tables/basic',
                parentKey: 'tables',
            },
            {
                key: 'advanced',
                label: 'Advanced Table',
                isTitle: false,
                url: '/tables/advanced',
                parentKey: 'tables',
            },
        ],
    },
    {
        key: 'charts',
        label: 'Charts',
        isTitle: false,
        icon: 'mdi mdi-chart-donut-variant',
        children: [
            {
                key: 'apex',
                label: 'ApexChart',
                isTitle: false,
                url: '/charts/apex',
                parentKey: 'charts',
            },
            {
                key: 'chartjs',
                label: 'ChartJS',
                isTitle: false,
                url: '/charts/chartjs',
                parentKey: 'charts',
            },
        ],
    },
    {
        key: 'maps',
        label: 'Maps',
        isTitle: false,
        icon: 'mdi mdi-map-outline',
        children: [
            {
                key: 'google',
                label: 'Google',
                isTitle: false,
                url: '/maps/google',
                parentKey: 'maps',
            },
            {
                key: 'vector',
                label: 'Vector',
                isTitle: false,
                url: '/maps/vector',
                parentKey: 'maps',
            },
        ],
    },
    {
        key: 'multi-level',
        label: 'Multi Level',
        isTitle: false,
        children: [
            {
                key: 'second-level',
                label: 'Second Level',
                isTitle: false,
                parentKey: 'multi-level',
                children: [
                    {
                        key: 'second-level-1',
                        label: 'Item 1',
                        isTitle: false,
                        parentKey: 'second-level',
                        url: '',
                    },
                    {
                        key: 'second-level-2',
                        label: 'Item 2',
                        isTitle: false,
                        parentKey: 'second-level',
                        url: '',
                    },
                ],
            },
            {
                key: 'third-level',
                label: 'Third Level',
                isTitle: false,
                parentKey: 'multi-level',
                children: [
                    {
                        key: 'third-level-1',
                        label: 'Item 1',
                        isTitle: false,
                        parentKey: 'third-level',
                        url: '',
                    },
                    {
                        key: 'third-level-2',
                        label: 'Item 2',
                        isTitle: false,
                        parentKey: 'third-level',
                        url: '',
                    },
                ],
            },
        ],
    },
];

const HORIZONTAL_MENU_ITEMS: MenuItemTypes[] = [
    {
        key: 'dashboard',
        label: 'Dashboard',
        isTitle: false,
        icon: 'mdi mdi-view-dashboard',
        url: '/dashboard',
    },
    {
        key: 'base-ui',
        icon: 'mdi mdi-invert-colors',
        label: 'UI Elements',
        isTitle: true,
        children: [
            {
                key: 'base-ui-buttons',
                label: 'Buttons',
                url: '/base-ui/buttons',
                parentKey: 'base-ui',
            },
        ],
    },
    {
        key: 'dashboard',
        label: 'Dashboard',
        isTitle: false,
        icon: 'mdi mdi-view-dashboard-outline',
        badge: { variant: 'success', text: '9+' },
        url: '/dashboard',
    },
    {
        key: 'tasks',
        label: 'Tasks',
        isTitle: false,
        icon: 'mdi mdi-clipboard-outline',
        url: '/tasks',
        children: [
            {
                key: 'tasks-kanban-board',
                label: 'Kanban Board',
                isTitle: false,
                url: '/tasks/kanban-board',
                parentKey: 'tasks',
            },
            {
                key: 'tasks-details',
                label: 'Details',
                isTitle: false,
                url: '/tasks/details',
                parentKey: 'tasks',
            },
        ],
    },
    {
        key: 'auth',
        label: 'Auth Pages',
        isTitle: false,
        icon: 'mdi mdi-account-multiple-plus-outline',
        children: [
            {
                key: 'auth-login',
                label: 'Log In',
                isTitle: false,
                url: '/auth/login',
                parentKey: 'auth',
            },
            {
                key: 'auth-register',
                label: 'Register',
                isTitle: false,
                url: '/auth/register',
                parentKey: 'auth',
            },
            {
                key: 'auth-forget-password',
                label: 'Recover Password',
                isTitle: false,
                url: '/auth/forget-password',
                parentKey: 'auth',
            },
            {
                key: 'auth-lock-screen',
                label: 'Lock Screen',
                isTitle: false,
                url: '/auth/lock-screen',
                parentKey: 'auth',
            },
        ],
    },
    {
        key: 'pages',
        label: 'Extra Pages',
        isTitle: false,
        icon: 'mdi mdi-file-multiple-outline',
        children: [
            {
                key: 'starter',
                label: 'Starter',
                isTitle: false,
                url: '/pages/starter',
                parentKey: 'pages',
            },
            {
                key: 'pricing',
                label: 'Pricing',
                isTitle: false,
                url: '/pages/pricing',
                parentKey: 'pages',
            },
            {
                key: 'timeline',
                label: 'Timeline',
                isTitle: false,
                url: '/pages/timeline',
                parentKey: 'pages',
            },
            {
                key: 'invoice',
                label: 'Invoice',
                isTitle: false,
                url: '/pages/invoice',
                parentKey: 'pages',
            },
            {
                key: 'faq',
                label: 'FAQs',
                isTitle: false,
                url: '/pages/faq',
                parentKey: 'pages',
            },
            {
                key: 'gallery',
                label: 'Gallery',
                isTitle: false,
                url: '/pages/gallery',
                parentKey: 'pages',
            },
            {
                key: 'error-404',
                label: 'Error 404',
                isTitle: false,
                url: '/error-404',
                parentKey: 'pages',
            },
            {
                key: 'error-500',
                label: 'Error 500',
                isTitle: false,
                url: '/error-500',
                parentKey: 'pages',
            },
            {
                key: 'maintenance',
                label: 'Maintenance',
                isTitle: false,
                url: '/maintenance',
                parentKey: 'pages',
            },
            {
                key: 'coming-soon',
                label: 'Coming Soon',
                isTitle: false,
                url: '/coming-soon',
                parentKey: 'pages',
            },
            {
                key: 'landing',
                label: 'Landing',
                isTitle: false,
                url: '/landing',
                parentKey: 'pages',
            },
        ],
    },
    {
        key: 'projects',
        label: 'Projects',
        isTitle: false,
        icon: 'mdi mdi-briefcase-variant-outline',
        url: '/projects',
    },
    {
        key: 'base-ui',
        label: 'Base UI',
        isTitle: false,
        icon: 'mdi mdi-briefcase-outline',
        children: [
            {
                key: 'buttons',
                label: 'Buttons',
                isTitle: false,
                url: '/base-ui/buttons',
                parentKey: 'base-ui',
            },
            {
                key: 'cards',
                label: 'Cards',
                isTitle: false,
                url: '/base-ui/cards',
                parentKey: 'base-ui',
            },
            {
                key: 'avatars',
                label: 'Avatars',
                isTitle: false,
                url: '/base-ui/avatars',
                parentKey: 'base-ui',
            },
            {
                key: 'tabs-accordions',
                label: 'Tabs & Accordions',
                isTitle: false,
                url: '/base-ui/tabs-accordions',
                parentKey: 'base-ui',
            },
            {
                key: 'modals',
                label: 'Modals',
                isTitle: false,
                url: '/base-ui/modals',
                parentKey: 'base-ui',
            },
            {
                key: 'progress',
                label: 'Progress',
                isTitle: false,
                url: '/base-ui/progress',
                parentKey: 'base-ui',
            },
            {
                key: 'notifications',
                label: 'Notifications',
                isTitle: false,
                url: '/base-ui/notifications',
                parentKey: 'base-ui',
            },
            {
                key: 'offcanvas',
                label: 'Offcanvas',
                isTitle: false,
                url: '/base-ui/offcanvas',
                parentKey: 'base-ui',
            },
            {
                key: 'placeholders',
                label: 'Placeholders',
                isTitle: false,
                url: '/base-ui/placeholders',
                parentKey: 'base-ui',
            },
            {
                key: 'spinners',
                label: 'Spinners',
                isTitle: false,
                url: '/base-ui/spinners',
                parentKey: 'base-ui',
            },
            {
                key: 'images',
                label: 'Images',
                isTitle: false,
                url: '/base-ui/images',
                parentKey: 'base-ui',
            },
            {
                key: 'carousel',
                label: 'Carousel',
                isTitle: false,
                url: '/base-ui/carousel',
                parentKey: 'base-ui',
            },
            {
                key: 'embedvideo',
                label: 'Embed Video',
                isTitle: false,
                url: '/base-ui/embedvideo',
                parentKey: 'base-ui',
            },
            {
                key: 'dropdowns',
                label: 'Dropdowns',
                isTitle: false,
                url: '/base-ui/dropdowns',
                parentKey: 'base-ui',
            },
            {
                key: 'popovers-tooltips',
                label: 'Tooltips & Popovers',
                isTitle: false,
                url: '/base-ui/popovers-tooltips',
                parentKey: 'base-ui',
            },
            {
                key: 'general',
                label: 'General UI',
                isTitle: false,
                url: '/base-ui/general',
                parentKey: 'base-ui',
            },
            {
                key: 'typography',
                label: 'Typography',
                isTitle: false,
                url: '/base-ui/typography',
                parentKey: 'base-ui',
            },
            {
                key: 'grid',
                label: 'Grid',
                isTitle: false,
                url: '/base-ui/grid',
                parentKey: 'base-ui',
            },
        ],
    },
    {
        key: 'widgets',
        label: 'Widgets',
        isTitle: false,
        icon: 'mdi mdi-gift-outline',
        url: '/widgets',
    },
    {
        key: 'extended-ui',
        label: 'Extended UI',
        isTitle: false,
        icon: 'mdi mdi-layers-outline',
        badge: { variant: 'info', text: 'Hot' },
        children: [
            {
                key: 'nestable',
                label: 'Nestable',
                isTitle: false,
                url: '/extended-ui/nestable',
                parentKey: 'extended-ui',
            },
            {
                key: 'rangesliders',
                label: 'Range Sliders',
                isTitle: false,
                url: '/extended-ui/rangesliders',
                parentKey: 'extended-ui',
            },
            {
                key: 'sweet-alert',
                label: 'Sweet Alert',
                isTitle: false,
                url: '/extended-ui/sweet-alert',
                parentKey: 'extended-ui',
            },
            {
                key: 'tour',
                label: 'Tour',
                isTitle: false,
                url: '/extended-ui/tour',
                parentKey: 'extended-ui',
            },
            {
                key: 'treeview',
                label: 'Tree View',
                isTitle: false,
                url: '/extended-ui/treeview',
                parentKey: 'extended-ui',
            },
        ],
    },
    {
        key: 'icons',
        label: 'Icons',
        isTitle: false,
        icon: 'mdi mdi-shield-outline',
        children: [
            {
                key: 'feather',
                label: 'Feather Icons',
                isTitle: false,
                url: '/icons/feather',
                parentKey: 'icons',
            },
            {
                key: 'mdi',
                label: 'Material Design IIcons',
                isTitle: false,
                url: '/icons/mdi',
                parentKey: 'icons',
            },
            {
                key: 'dripicons',
                label: 'Dripicons',
                isTitle: false,
                url: '/icons/dripicons',
                parentKey: 'icons',
            },
            {
                key: 'font-awesome',
                label: 'Font Awesome 5',
                isTitle: false,
                url: '/icons/font-awesome',
                parentKey: 'icons',
            },
            {
                key: 'themify',
                label: 'Themify',
                isTitle: false,
                url: '/icons/themify',
                parentKey: 'icons',
            },
        ],
    },
    {
        key: 'forms',
        label: 'Forms',
        isTitle: false,
        icon: 'mdi mdi-texture',
        children: [
            {
                key: 'basic',
                label: 'General Elements',
                isTitle: false,
                url: '/forms/basic',
                parentKey: 'forms',
            },
            {
                key: 'advanced',
                label: 'Advanced',
                isTitle: false,
                url: '/forms/advanced',
                parentKey: 'forms',
            },
            {
                key: 'validation',
                label: 'Validation',
                isTitle: false,
                url: '/forms/validation',
                parentKey: 'forms',
            },
            {
                key: 'wizard',
                label: 'Wizard',
                isTitle: false,
                url: '/forms/wizard',
                parentKey: 'forms',
            },
            {
                key: 'upload',
                label: 'File Upload',
                isTitle: false,
                url: '/forms/upload',
                parentKey: 'forms',
            },
            {
                key: 'editors',
                label: 'Editors',
                isTitle: false,
                url: '/forms/editors',
                parentKey: 'forms',
            },
        ],
    },
    {
        key: 'tables',
        label: 'Tables',
        isTitle: false,
        icon: 'mdi mdi-table',
        children: [
            {
                key: 'basic',
                label: 'Basic Table',
                isTitle: false,
                url: '/tables/basic',
                parentKey: 'tables',
            },
            {
                key: 'advanced',
                label: 'Advanced Table',
                isTitle: false,
                url: '/tables/advanced',
                parentKey: 'tables',
            },
        ],
    },
    {
        key: 'charts',
        label: 'Charts',
        isTitle: false,
        icon: 'mdi mdi-chart-donut-variant',
        children: [
            {
                key: 'apex',
                label: 'ApexChart',
                isTitle: false,
                url: '/charts/apex',
                parentKey: 'charts',
            },
            {
                key: 'chartjs',
                label: 'ChartJS',
                isTitle: false,
                url: '/charts/chartjs',
                parentKey: 'charts',
            },
        ],
    },
    {
        key: 'maps',
        label: 'Maps',
        isTitle: false,
        icon: 'mdi mdi-map-outline',
        children: [
            {
                key: 'google',
                label: 'Google',
                isTitle: false,
                url: '/maps/google',
                parentKey: 'maps',
            },
            {
                key: 'vector',
                label: 'Vector',
                isTitle: false,
                url: '/maps/vector',
                parentKey: 'maps',
            },
        ],
    },
    {
        key: 'multi-level',
        label: 'Multi Level',
        isTitle: false,
        children: [
            {
                key: 'second-level',
                label: 'Second Level',
                isTitle: false,
                parentKey: 'multi-level',
                children: [
                    {
                        key: 'second-level-1',
                        label: 'Item 1',
                        isTitle: false,
                        parentKey: 'second-level',
                        url: '',
                    },
                    {
                        key: 'second-level-2',
                        label: 'Item 2',
                        isTitle: false,
                        parentKey: 'second-level',
                        url: '',
                    },
                ],
            },
            {
                key: 'third-level',
                label: 'Third Level',
                isTitle: false,
                parentKey: 'multi-level',
                children: [
                    {
                        key: 'third-level-1',
                        label: 'Item 1',
                        isTitle: false,
                        parentKey: 'third-level',
                        url: '',
                    },
                    {
                        key: 'third-level-2',
                        label: 'Item 2',
                        isTitle: false,
                        parentKey: 'third-level',
                        url: '',
                    },
                ],
            },
        ],
    },
];

export { MENU_ITEMS, HORIZONTAL_MENU_ITEMS };
